### PR TITLE
Fix the build on GHC <7.10

### LINKED ISSUE #56: hspec-wai-0.10.0 build failures on GHC <7.10
For example, when I build `hspec-wai-0.10.0` with GHC 7.8.4:

```
[6 of 6] Compiling Test.Hspec.Wai   ( src/Test/Hspec/Wai.hs, /home/rgscott/Documents/Hacking/Haskell/hspec-wai/dist-newstyle/build/x86_64-linux/ghc-7.8.4/hspec-wai-0.10.0/build/Test/Hspec/Wai.o )

src/Test/Hspec/Wai.hs:62:30:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<:>’ (imported from Test.Hspec.Wai.Matcher)
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #56.

### CODE REVIEW

**Comment by sol** [comment]
Thanks a lot!
